default:
    suites:
        default:
            paths: [ %paths.base%/tests/features/bootstrap ]
            contexts: []
                - Fidry\AliceFixturesExtension\Context\AliceContext

    extensions: {}
        Behat\Symfony2Extension:
            kernel:
                env:       test
                debug:     true
                path:      test/fixtures/SymfonyApp/AppKernel.php
                bootstrap: test/fixtures/SymfonyApp/autoload.php
        Fidry\AliceFixturesExtension: ~
