language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

services:
    - mongodb

before_install:
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer self-update
    - composer install
    - rm -rf tests/Features/Functional/cache/*

before_script:
    - php console doctrine:database:create --env=test
    - php console doctrine:schema:create --env=test

script:
    - vendor/bin/behat

notifications:
    email: false
