language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer self-update
    - composer install
    - rm -rf Features/SymfonyApp/cache/*
    - bash -c 'if ([ "hhvm" != "$TRAVIS_PHP_VERSION" ] && [ "hhvm-nightly" != "$TRAVIS_PHP_VERSION" ] && [ "nightly" != "$TRAVIS_PHP_VERSION" ]); then wget https://scrutinizer-ci.com/ocular.phar; fi;'

before_script:
    - bash -c 'php console doctrine:database:create --env=test'
    - bash -c 'php console doctrine:schema:create --env=test'

script:
    - vendor/bin/behat

after_script:
  - bash -c 'if ([ "hhvm" != "$TRAVIS_PHP_VERSION" ] && [ "hhvm-nightly" != "$TRAVIS_PHP_VERSION" ] && [ "nightly" != "$TRAVIS_PHP_VERSION" ]); then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'
