language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer self-update
    - composer install
    - rm -rf test/Features/SymfonyApp/cache/*

before_script:
    - bash -c 'php console doctrine:database:create --env=test'
    - bash -c 'php console doctrine:schema:create --env=test'

script:
    - vendor/bin/behat
